### ISSUE TITLE
Services addition tracking feature

### ISSUE THREAD

**Issue by Shocktrooper** [gitlabhq/terraform-provider-gitlab#607]
### Purpose
To serve as  a wholistic tracking ticket of all of the services that are available via the API and what their integration progress into this terraform provider.  This ticket should be kept up to date as new service integrations are released by GitLab, [go-gitlab](https://github.com/xanzy/go-gitlab) updates its services integration and this project integrates the service into the provider

### Services Tracking list

Complete List of services sourced from [here](https://docs.gitlab.com/ce/api/services.html) on 4/19/21
This list was cross referenced from [here](https://github.com/xanzy/go-gitlab/blob/master/services.go) with the GitLab service API page
- [ ] Asana (Needs go-gitlab work)
- [ ] Assembla (Needs go-gitlab work)
- [ ] Atlassian Bamboo CI (Needs go-gitlab work)
- [ ] Bugzilla (Needs go-gitlab work)
- [ ] Buildkite (Needs go-gitlab work)
- [ ] Campfire (Needs go-gitlab work)
- [ ] Unify Circuit (Needs go-gitlab work)
- [ ] Webex Teams (Needs go-gitlab work)
- [ ] Custom Issue Tracker
- [ ] Drone CI
- [ ] Emails on push (Needs go-gitlab work)
- [ ] Confluence service (Needs go-gitlab work)
- [ ] External wiki
- [ ] Flowdock (Needs go-gitlab work)
- [x] GitHub
- [ ] Hangouts Chat (Needs go-gitlab work)
- [ ] Irker (IRC gateway) (Needs go-gitlab work)
- [x] Jira
- [ ] Slack slash commands (Needs go-gitlab work)
- [ ] Mattermost slash commands (Needs go-gitlab work)
- [ ] Packagist (Needs go-gitlab work)
- [x] Pipeline-Emails
- [ ] PivotalTracker (Needs go-gitlab work)
- [ ] Prometheus
- [ ] Pushover (Needs go-gitlab work)
- [ ] Redmine (Needs go-gitlab work)
- [x] Slack notifications
- [ ] Microsoft Teams
- [ ] Mattermost notifications
- [ ] JetBrains TeamCity CI (Needs go-gitlab work)
- [ ] Jenkins CI
- [ ] MockCI (Needs go-gitlab work)
- [ ] YouTrack (Needs go-gitlab work)

### References
- https://github.com/xanzy/go-gitlab
- https://docs.gitlab.com/ce/api/services.html

### Other Ticket References
- #192 
- #308 
- #462
